### ISSUE TITLE
About the update problem about the script "downloadDB.py"

### ISSUE THREAD

**Issue by qazwsx1995** [AnantharamanLab/ViWrap#10]
![image](https://user-images.githubusercontent.com/65820716/223068777-4874f952-8f48-425f-bd31-4b49682e3f51.png)
![993ed5a7f5bcbff5ea7d3e25e192b5f](https://user-images.githubusercontent.com/65820716/223068810-8d72e681-7986-421e-840b-a63da7c239af.png)
There is only viral.1.protein.gpff.gz and viral.1.protein.faa.gz in Refseq, but the commands of multiple file downloads are written in the script

**Comment by qazwsx1995** [comment]
@ChaoLab

**Comment by ChaoLab** [comment]
Previous, there are multiple (4) sub-files for this viral refseq datasets. My current scripts can deal with both cases
