### ISSUE TITLE
A suggestion about the operation of the software

### ISSUE THREAD

**Issue by qazwsx1995** [AnantharamanLab/ViWrap#13]
Hi,
Would you like to interrupt the ViWrap software due to calculation failure, and then repeat the function that can continue to calculate the result of the last interruption, which can also prevent the waste of resources from the repeated calculation of large data (if the software is interrupted due to a calculation error in the middle of the software) ?

**Comment by Microbion** [comment]
Wrapper in nextflow or snakemake would be better. It's more easier to deploy ViWrap in HPCC.
