### ISSUE TITLE
🐎 ⬆️ Split assembly and speed up Vibrant

### ISSUE THREAD

**Issue by Sidduppal** [AnantharamanLab/ViWrap#14]
Hey, thanks for this amazing pipeline. I was wondering if there's a way to split the assembly and run them in parallel to speed up Vibrant. 
Based on my understanding Vibrant is  is reading all the scaffolds into memory during the `VIBRANT_extract_nucleotide.py` step. Based on some of the issues on Vibrant's GitHub page it seems like it's much faster to split the assembly and run Vibrant in parallel. Is there a way I can do that and still run ViWrap or is it possible to incorporate such a feature in ViWrap?

I'm on a server with 128 Gb of RAM (plus 128 Gb of swamp) and running Vibrant with 40 cpus. It's been a day and vibrant is still on the `VIBRANT_extract_nucleotide.py` step.

Thanks!

**Comment by ChaoLab** [comment]
Maybe you can try the lastest version using geNomad as the virus identification tool. The latest version of v1.3.0 has been released now.
