### ISSUE TITLE
No results were produced by virsorter2

### ISSUE THREAD

**Issue by quliping** [AnantharamanLab/ViWrap#17]
ViWrap is a good pepeline, but I got some problems. Here is my command line:
ViWrap run --input_metagenome 03_connected_assembly/${line}.fasta \
            --input_reads /public/home/qlp/seamount-meta/00_new_workdir/01_READ_QC/${line}_1.fastq,/public/home/qlp/seamount-meta/00_new_workdir/01_READ_QC/${line}_2.fastq \
            --out_dir /public/home/qlp/seamount-meta/00_new_workdir/12_VIRUS_out/${1}/${line} \
            --db_dir /public/data/database/ViWrap-database \
            --identify_method vs \
            --conda_env_dir /public/data/database/ViWrap_conda_environments \
            --threads 96 \
            --input_length_limit 2000 \
            --custom_MAGs_dir /public/home/qlp/seamount-meta/00_new_workdir/12_VIRUS_host/${1} \
            --iPHoP_db_custom /public/home/qlp/seamount-meta/00_new_workdir/12_VIRUS_custom_db/${1}.db

However, virsorter2 produced no results and led to the failure of subsequent steps. It seems that the virsorter2 step was not completed properly and no virus were identified, but the ViWrap proceeded to the next step.
![image](https://github.com/AnantharamanLab/ViWrap/assets/39583607/bf89e7ae-7f25-4a1e-9438-c616b65bd056)
![image](https://github.com/AnantharamanLab/ViWrap/assets/39583607/b0114ade-3d59-42f5-a8d8-cf86314bc054)

**Comment by vietbio** [comment]
You may check if the config of virsorter DB is correct 

conda activate /public/data/database/ViWrap_conda_environments/ViWrap-vs2

virsorter config --show

Check the last line DBDIR. If that is not /public/data/database/ViWrap-database/VirSorter2_db, then run

virsorter config --init-source --db-dir /public/data/database/ViWrap-database/VirSorter2_db

Hope that can be helpful,

Hieu Cao

**Comment by quliping** [comment]
Thanks for your reply. However, your suggestion doesn't work. In fact, the config of virsorter DB was correct.
![image](https://github.com/AnantharamanLab/ViWrap/assets/39583607/a319cf7c-9a03-4b7b-a86c-8936de5599de)

 I also tried runinig virsorter2 based on the conda environment directly, while it alos didn't work. I got some new error from virsorter2. Both of the test-data of ViWrap and virsorter2 were tested. I think there were something wrong with virsorter2 rather than VirWrap. I also asked the developer of virsorter2 on the github but they didn't reply to me. I would be very grateful If you could help me see what's going on.
[virsorter-test-data.log.txt](https://github.com/AnantharamanLab/ViWrap/files/11859046/virsorter-test-data.log.txt)
[virsorter-test-data.zip](https://github.com/AnantharamanLab/ViWrap/files/11859050/virsorter-test-data.zip)
[virwrap-test-data.log](https://github.com/AnantharamanLab/ViWrap/files/11859051/virwrap-test-data.log)

Besides, I analyzed some metagenome data successfully using virsorter2 v2.2.3 conda environment before. Then, VrWrap installed a new environment for virsorter2 (v2.2.4) in the other directory. It was strange that both of them were not work any more. I also tried the data which were analyzed successfully before.  Seems all running were crashed during the hmmsearch step. 

Sincerely,

Liping Qu

**Comment by WoCer2019** [comment]
The same error.

**Comment by quliping** [comment]
> The same error.

This problem was solved. Please see this question which was asked by myself at the virsorter2 page: [https://github.com/jiarong/VirSorter2/issues/167](url)

Change the default `/tmp` in `LOCAL_SCRATCH` variable in the config file of virsorter2. The path of my config file was  `/public/data/database/ViWrap_conda_environments/ViWrap-vs2/lib/python3.8/site-packages/virsorter/template-config.yaml`. You can use your own directory rather than the root dir '/tmp'.  Permission issues prevent hmmsearch from deleting certain temporary files and result in this error. 

@vietbio I think there are some conflicts between my own virsorter2 conda environment and ViWrap virsorter2 conda environment because this error occurred after ViWrap installed the new virsorter2 conda environment. The variable of 'DBDIR' in the config file of the new virsorter2 environment was also set to the old database path rather than the new path set by ViWrap. Of course, this problem is not very important. 

Besides, it seems that some not-root users do not have permission  for the checkV database. The defuault permission is '750' and ViWrap failed to successfully run checkV. I  Maybe something like 'chmod 755 -R /PATH/to/database/of/checkv_database' should be added in the ViWrap scripts.  I'm not sure if anyone else has encountered  this problem.

**Comment by WoCer2019** [comment]
> > The same error.
> 
> This problem was solved. Please see this question which was asked by myself at the virsorter2 page: [https://github.com/jiarong/VirSorter2/issues/167](url)
> 
> Change the default `/tmp` in `LOCAL_SCRATCH` variable in the config file of virsorter2. The path of my config file was `/public/data/database/ViWrap_conda_environments/ViWrap-vs2/lib/python3.8/site-packages/virsorter/template-config.yaml`. You can use your own directory rather than the root dir '/tmp'. Permission issues prevent hmmsearch from deleting certain temporary files and result in this error.
> 
> @vietbio I think there are some conflicts between my own virsorter2 conda environment and ViWrap virsorter2 conda environment because this error occurred after ViWrap installed the new virsorter2 conda environment. The variable of 'DBDIR' in the config file of the new virsorter2 environment was also set to the old database path rather than the new path set by ViWrap. Of course, this problem is not very important.
> 
> Besides, it seems that some not-root users do not have permission for the checkV database. The defuault permission is '750' and ViWrap failed to successfully run checkV. I Maybe something like 'chmod 755 -R /PATH/to/database/of/checkv_database' should be added in the ViWrap scripts. I'm not sure if anyone else has encountered this problem.



Thank you!
