### ISSUE TITLE
Run error: No such file or directory (final-viral-score.tsv)

### ISSUE THREAD

**Issue by maocheng2020** [AnantharamanLab/ViWrap#25]
Hi! This tool is very convenient to use. I'm getting some errors during use, I hope you can help me check it. Thank you!

The issued command is:
ViWrap run \
--input_metagenome **all_final_assembly.fasta** \
--input_reads M1_1.fastq,M1_2.fastq,M2_1.fastq,M2_2.fastq,M3_1.fastq,M3_2.fastq,M4_1.fastq,M4_2.fastq,K1_1.fastq,K1_2.fastq,K2_1.fastq,K2_2.fastq,K3_1.fastq,K3_2.fastq,K4_1.fastq,K4_2.fastq \
--out_dir MK_out \
--db_dir ViWrap_db \
--conda_env_dir /home/miniconda3/envs/ViWrap \
--identify_method vb-vs --threads 20 --input_length_limit 5000 \
--custom_MAGs_dir /root/viwrap/86bins \
--iPHoP_db_custom /root/viwrap/iPHoP_db_custom_MK

[2023-11-10 14:53:45] | Run VIBRANT-VirSorter2 method. Run VirSorter2 to identify viruses from input metagenome. Finished
[2023-11-10 14:53:53] | Run VIBRANT-VirSorter2 method. Run CheckV to QC and trim viruses identified from VirSorter2. Finished
Traceback (most recent call last):
  File "/root/ViWrap/ViWrap", line 173, in <module>
    output = cli()
  File "/root/ViWrap/ViWrap", line 167, in cli
    args["func"](args)
  File "/data/ViWrap/ViWrap/scripts/master_run.py", line 313, in main
    scripts.module.screen_virsorter2_result(inner_vs_outdir, keep1_list_file, keep2_list_file, discard_list_file, manual_check_list_file)
  File "/data/ViWrap/ViWrap/scripts/module.py", line 1529, in screen_virsorter2_result
    with open(final_viral_score, 'r') as lines:
FileNotFoundError: [Errno 2] No such file or directory: '/root/viwrap/MK_out/00_VIBRANT_VirSorter_MK_assembly/VirSorter_MK_assembly/pass/final-viral-score.tsv'

I'm guessing the problem might be with the **all_final_assembly.fasta** file.
Due to the lack of memory on my computer, all_final_assembly.fasta is obtained by cating two final_assembly.fasta (co-assembly by megahit) directly together. Thank you!

**Comment by Reed628** [comment]
I met the same problem, how did you solve it

**Comment by maocheng2020** [comment]
> I met the same problem, how did you solve it @maocheng2020

final_assembly.fasta can't simply cats together as inputs, I run them separately.

**Comment by maocheng2020** [comment]
> I met the same problem, how did you solve it @maocheng2020

final_assembly.fasta can't simply cats together as inputs, I run them separately.

**Comment by maocheng2020** [comment]
> I met the same problem, how did you solve it @maocheng2020

final_assembly.fasta can't simply cat together as input, I run them separately.

**Comment by Charles-Lou** [comment]
please！How can I obtain the files in the 'custom_maGs_dir' folder？Thank you!
