### ISSUE TITLE
geNomad and ViWrap are not connected correctly

### ISSUE THREAD

**Issue by qazwsx1995** [AnantharamanLab/ViWrap#27]
geNomad and ViWrap are not connected correctly and the following error occurs. The output folder does not have the folder name that appears in this error.
![image](https://github.com/AnantharamanLab/ViWrap/assets/65820716/ac812a67-52a1-4630-88f0-d814ab2d9458)

**Comment by ChaoLab** [comment]
Maybe you were using the intermediate version when I was updating the scripts. The latest version of v1.3.0 has been released now.
