### ISSUE TITLE
Can't download databases

### ISSUE THREAD

**Issue by SaraOliva** [AnantharamanLab/ViWrap#32]
Hello, I want to thank you for the ViWrap application. Currently, I am trying to download the database with the following command: 

`ViWrap download --db_dir /home/soliva/dbs/viwrap  --conda_env_dir /home/soliva/anaconda3/envs/mamba/envs/viwrap --threads 20`

![imagen](https://github.com/AnantharamanLab/ViWrap/assets/75429526/be612d46-b5d4-47d9-8f66-e635fb5348a3)

I get the following and I don't see an indication that the database is being downloaded. I haven't been able to detect what I'm doing wrong. I have installed again and still have the same problem. If you can help me that would be great. Thank you!

**Comment by lamc97** [comment]
Hi, Sara. How did you solve this problem? I have the same issue. :(

**Comment by ewars** [comment]
Hi. 

You need to modify the file /path/to/ViWrap/scripts/master_downloader.py

I put # in the code for the already downloaded databases, so that it would not be executed. Too, the validation that the ViWrap_db folder already exists
