### ISSUE TITLE
conda env path is not present!

### ISSUE THREAD

**Issue by yyyangzd** [AnantharamanLab/ViWrap#38]
Greetings,
When run the code "ViWrap set_up_env --conda_env_dir ",several libraries (see attached) failed to install ; Error information is "XXX conda env path is not present!"? how to resolve this issue?? Thanks!
![{20582679-640C-45e7-8A9A-39F4836EAC51}](https://github.com/AnantharamanLab/ViWrap/assets/163529607/a9eae85b-d485-4577-ad76-5d43d54103e5)

**Comment by AmaliT** [comment]
Hi, I am getting similar issue. Are you able to share how you resolved this?
