### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'test_metaG_ViWrap_out/03_vConTACT2_outdir/genome_by_genome_overview.csv'

### ISSUE THREAD

**Issue by ChiLiubio** [AnantharamanLab/ViWrap#39]
Dear ViWrap team,
First thanks for the wonderful tool. I get such an error  for both the example data and my personal data. It seems like that the vConTACT2 is not working well. I would appreciate any suggestion.
![1711088277304](https://github.com/AnantharamanLab/ViWrap/assets/20815519/abfb669d-9788-484f-a0b4-7f3bb0a97216)

Best,
Chi

**Comment by Zoeyk9** [comment]
Hi, I’m encountering the same problem. Could you please share your solution if you’ve managed to resolve it?
