### ISSUE TITLE
Allowing for specific location of `custom_db` to solve permission and multi-users problems. 

### ISSUE THREAD

**Issue by patriciatran** [AnantharamanLab/ViWrap#5]
Currently, when we create or reuse a `custom_db` by specifying a folder MAGs in the `iPhop` step, it creates the database under the ViWrap_db folder (e.g.  `/public_path_for_everyone/ViWrap/ViWrap_db/custom_db/` . 

1- However, if multiple people are using the same server and creating/writing/removing that `custom_db` folder at simultaneously. 
2- This can also be an issue if the upstream folder `/public_path_for_everyone/ViWrap/ViWrap_db/` has read/write permission restrictions, which can be common in servers used by multiple people.

3- Another example is even if you already have ran iPhop and created a custom database and specify it using the `--iPHoP_db_custom_pre` argument, ViWrap will still tell you this error: 

```
[2023-02-16 09:56:35] | Pre-check inputings. In processing...
Please make sure that /public_path_for_everyone/ViWrap/ViWrap_db/iPHoP_db_custom is not present before ViWrap run. If present, please remove the folder
```

To fix both of these issues, @ChaoLab is in the process of allowing people to specify where the custom_db will be created!

Patricia

**Comment by ChaoLab** [comment]
I am adding "--iPHoP_db_custom" option to let users to assign the output of their custom iPHoP db. The address can be set by users to their own place; it does not need to be within `/public_path_for_everyone/ViWrap/ViWrap_db`.
