### ISSUE TITLE
Issure about Step 3 Set up the other conda

### ISSUE THREAD

**Issue by Cczyf** [AnantharamanLab/ViWrap#57]
Hello ,Developer
when i run ViWrap set_up_env --conda_env_dir , error information is "ViWrap found no command",do you know how to resolve it?? thans!
![1734784471012](https://github.com/user-attachments/assets/89d13905-5d39-4afc-b7eb-61ff7b1f062e)

**Comment by ewars** [comment]
Hi.
 You need to put like directory to the ViWrap folder where the ViWrap file is.
![image](https://github.com/user-attachments/assets/e9454622-0fd6-4116-b0ba-219bc840b156)

**Comment by Cczyf** [comment]
> Hi. You need to put like directory to the ViWrap folder where the ViWrap file is. and always use the commands:
> 
> chmod +x ViWrap scripts/*.py
> 
> PATH=`pwd`:$PATH
> 
> ![image](https://private-user-images.githubusercontent.com/27823492/397937394-e9454622-0fd6-4116-b0ba-219bc840b156.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4MzgzOTAsIm5iZiI6MTczNDgzODA5MCwicGF0aCI6Ii8yNzgyMzQ5Mi8zOTc5MzczOTQtZTk0NTQ2MjItMGZkNi00MTE2LWIwYmEtMjE5YmM4NDBiMTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDAzMjgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3N2Y1Y2U2YmUwZGRlOGVjMjZhNTRiMDI2MWZjZWNlYThhNDUwZTBkZDA5NmM2ZWQ0ZTEyNmRkMWY1ODgwMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dOS5Tac5REbKhvKqUoYm-Y4nptn3CdjgO3sjCakK6nY)
Thanks, I have resolve this issure ,but when i run set up, another new issure happened likes all conda environments required by ViWrap env path is not present
![微信图片_20241222112621](https://github.com/user-attachments/assets/2e3f9184-e8e7-4980-883d-2f4e1a26d5ed)

**Comment by ewars** [comment]
Hi.

Use the .yaml files in the yamls folder to install each environment.

**Comment by Cczyf** [comment]
> Hi.
> 
> Use the .yaml files in the yamls folder to install each environment.



> Hi.
> 
> Use the .yaml files in the yamls folder to install each environment.

Thanks a lot, I really appreciate it

**Comment by tomj2005101** [comment]
Hi，I had the same problem, how did you solve it？
> Thanks a lot, I really appreciate it

**Comment by Cczyf** [comment]
> Hi，I had the same problem, how did you solve it？
> 
> > Thanks a lot, I really appreciate it
 



hi, tomj, sorry for my late answer, you can use the .yaml files in the yamls folder to install each environment.
e.g. 
conda env create -f /path/to/ViWrap/yamls/ViWrap-CheckV.yml -p /path/to/ViWrap_conda_environments/ViWrap-CheckV

conda env create -f /path/to/ViWrap/yamls/ViWrap-DVF.yml -p /path/to/ViWrap_conda_environments/ViWrap-DVF

when you install all environment, use the commands (ViWrap set_up_env) to verify your "ViWrap" environment

**Comment by brilliant2643** [comment]
> > Hi，I had the same problem, how did you solve it？
> > > Thanks a lot, I really appreciate it
> 
> hi, tomj, sorry for my late answer, you can use the .yaml files in the yamls folder to install each environment. e.g. conda env create -f /path/to/ViWrap/yamls/ViWrap-CheckV.yml -p /path/to/ViWrap_conda_environments/ViWrap-CheckV
> 
> conda env create -f /path/to/ViWrap/yamls/ViWrap-DVF.yml -p /path/to/ViWrap_conda_environments/ViWrap-DVF
> 
> when you install all environment, use the commands (ViWrap set_up_env) to verify your "ViWrap" environment

Hi! I tried this method to install all the environments, however, when I run the viwrap command with all the identify methods, I get errors like 'no such file or directory...', I'm wondering if I install the environments successfully. How can I check if my environment is correcely set up?

**Comment by yyyangzd** [comment]
> > > Hi，I had the same problem, how did you solve it？
> > > > Thanks a lot, I really appreciate it
> > 
> > 
> > hi, tomj, sorry for my late answer, you can use the .yaml files in the yamls folder to install each environment. e.g. conda env create -f /path/to/ViWrap/yamls/ViWrap-CheckV.yml -p /path/to/ViWrap_conda_environments/ViWrap-CheckV
> > conda env create -f /path/to/ViWrap/yamls/ViWrap-DVF.yml -p /path/to/ViWrap_conda_environments/ViWrap-DVF
> > when you install all environment, use the commands (ViWrap set_up_env) to verify your "ViWrap" environment
> 
> Hi! I tried this method to install all the environments, however, when I run the viwrap command with all the identify methods, I get errors like 'no such file or directory...', I'm wondering if I install the environments successfully. How can I check if my environment is correcely set up?

Hi, did you solve this problem?

**Comment by Cczyf** [comment]
> > > Hi，I had the same problem, how did you solve it？
> > > > Thanks a lot, I really appreciate it
> > 
> > 
> > hi, tomj, sorry for my late answer, you can use the .yaml files in the yamls folder to install each environment. e.g. conda env create -f /path/to/ViWrap/yamls/ViWrap-CheckV.yml -p /path/to/ViWrap_conda_environments/ViWrap-CheckV
> > conda env create -f /path/to/ViWrap/yamls/ViWrap-DVF.yml -p /path/to/ViWrap_conda_environments/ViWrap-DVF
> > when you install all environment, use the commands (ViWrap set_up_env) to verify your "ViWrap" environment
> 
> Hi! I tried this method to install all the environments, however, when I run the viwrap command with all the identify methods, I get errors like 'no such file or directory...', I'm wondering if I install the environments successfully. How can I check if my environment is correcely set up?

可能装错了吧，你发个截图看看呢

**Comment by kangluyao** [comment]
@Cczyf 请问安装成功后的环境目录是这样的吗？

<img width="580" height="255" alt="Image" src="https://github.com/user-attachments/assets/7b3b9170-cc03-4852-a957-26e8fb7ac10c" />

**Comment by Cczyf** [comment]
> [@Cczyf](https://github.com/Cczyf) 请问安装成功后的环境目录是这样的吗？
> 
> <img alt="Image" width="580" height="255" src="https://private-user-images.githubusercontent.com/56920269/477987162-7b3b9170-cc03-4852-a957-26e8fb7ac10c.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTUyMjc2OTUsIm5iZiI6MTc1NTIyNzM5NSwicGF0aCI6Ii81NjkyMDI2OS80Nzc5ODcxNjItN2IzYjkxNzAtY2MwMy00ODUyLWE5NTctMjZlOGZiN2FjMTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODE1VDAzMDk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMjFjM2RlZmNhMGM4NWMwZmU0ZTM2OGJlZTVhYTA0OGRkZjQxMTlmMjI5ODQ0NGViMGYyMjZjY2Q2NjMzNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DXH1wOoQpiP_QBFz6OScz2Jv5At1TxFqsr6UO9nUtaI">

是的
